version: '3.8'

services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    volumes:
      - ./data:/var/lib/besu
      - ./genesis.json:/config/genesis.json
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: >
      --genesis-file=/config/genesis.json
      --data-path=/var/lib/besu
      --network-id=2025
      --miner-enabled
      --miner-coinbase=0xB5De9620164CeD2453D1beC8FD9Ace3A451c134d
      --host-allowlist=*
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,WEB3,CLIQUE,ADMIN
      --rpc-http-cors-origins=all
      --rpc-http-host=0.0.0.0
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-api=ETH,NET,WEB3,CLIQUE
